[package]
name = "runwind"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
fallible-iterator = "0.2.0"
framehop = "0.7.1"
gimli = "0.26.2"
libc = "0.2.126"
log = "0.4.17"
macho-unwind-info = "0.3.0"
memmap2 = "0.5.5"
object = "0.29.0"
thiserror = "1.0.31"
