[package]
name = "runwind"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
framehop = "0.7.1"
gimli = "0.26.2"
libc = "0.2.126"
log = "0.4.17"
memmap2 = "0.5.5"
object = "0.29.0"
once_cell = "1.13.0"

[dev-dependencies]
addr2line = "0.18.0"
